### ISSUE TITLE
table z-index issue

### ISSUE THREAD

**Issue by dean-shanghai** [CodyHouse/cd-table-changelog#1]
File#: _1_table 
`.table--expanded .table__header .table__cell { z-index: 10; }` //z-index is a const

while, all the header nav components (eg.: mega nav), `z-index: var(--zindex-header);`,  //which is 3, so < 10

there'll be z-index problems, eg.: table header is above opened mega sub nav.

**Comment by sebastiano-guerriero** [comment]
This issue is fixed by adding a position relative and z-index 1 to the .table element:

```css
.table {
  position: relative;
  z-index: 1;
}
```

We will push this change to the component today.
